  spring:
    datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          format_sql: true
          show_sql: true
    h2:
      console:
        enabled: true
        path: /h2-console

    redis:
      host: localhost
      port: 6379
    cache:
      type: redis

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      com.PickOne: DEBUG
      org.springframework.transaction: TRACE
      org.springframework.orm: DEBUG